DEPTH = .

include openclsdkdefs.mk 

####
#
#  Targets
#
####

OPENCL			= 1
SAMPLE_EXE		= 1
EXE_TARGET 		= OpenCLTemplate
EXE_TARGET_INSTALL   	= OpenCLTemplate

####
#
#  C/CPP files
#
####

FILES 	= OpenCLTemplateMain OpenCLTemplate Timer
CLFILES	= OpenCLTemplate_Kernels.cl

include openclsdkrules.mk 

