DEPTH = .

include openclsdkdefs.mk 

####
#
#  Targets
#
####

OPENCL			= 1
SAMPLE_EXE		= 1
EXE_TARGET 		= FDTD2DDNG
EXE_TARGET_INSTALL   	= FDTD2DDNG

####
#
#  C/CPP files
#
####

FILES 	= FDTD2DDNGMain FDTD2DDNG Timer
CLFILES	= FDTD2DDNG_Kernels.cl

include openclsdkrules.mk 

