DEPTH = .

include openclsdkdefs.mk 

####
#
#  Targets
#
####

OPENCL			= 1
SAMPLE_EXE		= 1
EXE_TARGET 		= FDTD2D
EXE_TARGET_INSTALL   	= FDTD2D

####
#
#  C/CPP files
#
####

FILES 	= FDTD2DTMzMain FDTD2D
CLFILES	= FDTD2D_Kernels.cl

include openclsdkrules.mk 

