DEPTH = .

include openclsdkdefs.mk 

####
#
#  Targets
#
####

OPENCL			= 1
SAMPLE_EXE		= 1
EXE_TARGET 		= FDTD1DDNG
EXE_TARGET_INSTALL   	= FDTD1DDNG

####
#
#  C/CPP files
#
####

FILES 	= FDTD1DDNGMain FDTD1DDNG
CLFILES	= FDTD1DDNG_Kernels.cl

include openclsdkrules.mk 

